// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaeEajZn1FJa1IuG0TsIriGD0khRknLDs',
    appId: '1:1043370359027:web:f7ffc1eea123eef90bdf86',
    messagingSenderId: '1043370359027',
    projectId: 'fir-and-flutter-b3fe6',
    authDomain: 'fir-and-flutter-b3fe6.firebaseapp.com',
    storageBucket: 'fir-and-flutter-b3fe6.appspot.com',
    measurementId: 'G-DSHXY46MCY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB54AmLi5StSycsOobuxFLaY6KsSFs04J8',
    appId: '1:1043370359027:android:2715ca40171556ee0bdf86',
    messagingSenderId: '1043370359027',
    projectId: 'fir-and-flutter-b3fe6',
    storageBucket: 'fir-and-flutter-b3fe6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbTdy2LxwNMB_us45suQJWcFmkMUMVcnk',
    appId: '1:1043370359027:ios:12c4e77019a3be7c0bdf86',
    messagingSenderId: '1043370359027',
    projectId: 'fir-and-flutter-b3fe6',
    storageBucket: 'fir-and-flutter-b3fe6.appspot.com',
    iosBundleId: 'com.example.firstFirebaseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbTdy2LxwNMB_us45suQJWcFmkMUMVcnk',
    appId: '1:1043370359027:ios:12c4e77019a3be7c0bdf86',
    messagingSenderId: '1043370359027',
    projectId: 'fir-and-flutter-b3fe6',
    storageBucket: 'fir-and-flutter-b3fe6.appspot.com',
    iosBundleId: 'com.example.firstFirebaseProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaeEajZn1FJa1IuG0TsIriGD0khRknLDs',
    appId: '1:1043370359027:web:4a62ea90b1f595d40bdf86',
    messagingSenderId: '1043370359027',
    projectId: 'fir-and-flutter-b3fe6',
    authDomain: 'fir-and-flutter-b3fe6.firebaseapp.com',
    storageBucket: 'fir-and-flutter-b3fe6.appspot.com',
    measurementId: 'G-RW2MQLYB95',
  );
}
